// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $(window).scroll(function() {
      var top;
      top = $(document).scrollTop();
      console.log(top);
      if (top > 20) {
        return $('.navigation').addClass('shrink');
      } else {
        return $('.navigation').removeClass('shrink');
      }
    });
    $('.project').on('click', function(e) {
      var link;
      link = $(this).data('href');
      return window.open(link);
    });
    $('.mindfund').on('click', function(e) {
      $('#mindfund').removeClass('hideLeft');
      $('#mindfundstudio').addClass('hideRight');
      $('.selected').removeClass('selected');
      $(this).addClass('selected');
      return $('html').addClass('mindfund');
    });
    return $('.mindfundstudio').on('click', function(e) {
      $('#mindfund').addClass('hideLeft');
      $('#mindfundstudio').removeClass('hideRight');
      $('.selected').removeClass('selected');
      $(this).addClass('selected');
      return $('html').removeClass('mindfund');
    });
  });

}).call(this);
