// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    return $('.project').on('click', function(e) {
      var link;
      link = $(this).data('href');
      return window.open(link);
    });
  });

}).call(this);
